{
 "title": "Dashboard-GAO Xin-HAN Duqing",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory_app",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"Lab2_app\"}"
    }
   ]
  },
  {
   "title": "Memory_app_graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"Lab2_app\"}"
    }
   ]
  },
  {
   "title": "CPU_app",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"Lab2_app\"}"
    }
   ]
  },
  {
   "title": "CPU_app_graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"localhost:8010\", job=\"Lab2_app\"}"
    }
   ]
  },
  {
   "title": "CPU-node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "container_memory_cache" }
   ]
  },
  {
   "title": "CPU_system_graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total"
    }
   ]
  },
  {
   "title": "Memory_RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "container_memory_rss" }
   ]
  },
  {
   "title": "CPU_user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_user_seconds_total"
    }
   ]
  },
  {
   "title": "Memory Usage_all",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "container_memory_usage_bytes" }
   ]
  },
  {
   "title": "CPU_all_heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "node_cpu_seconds_total" }
   ]
  },
  {
   "title": "CPU_Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU_usage_graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total"
    }
   ]
  }
 ]
}